use_wandb: True # Set to False when debugging
device: "cuda:0"
diffusion_timesteps: 1001 # Using this +1 because i can go from 250 to 0 with a ddim stride of 10
epochs: 10000
epochs_per_checkpoint: 500
batch_size: 64
dropout: 0.1
obs_dropout: 0.025
target_dropout: 0.025
feature_vector_attention_dropout: 0.05
prev_state_attention_dropout: 0.15
iters_per_epoch: 50
lr: 0.00001
weight_decay: 0.01
test_size: 128
test_ddim_stride: 50
test_mode: "MODE_DDIM"
predict_mode: "PREDICT_X0"

EMA:
  ema_decay: 0.99
  ema_start: 200
  ema_update_rate: 1

features:
  frame_components: ["ROOT_POS", "ROOT_ROT", "JOINT_POS", "JOINT_ROT", "GRIPS"]
  rot_type: "DEFAULT" #ROT_6D, EXP_MAP, AXIS_ANGLE, QUAT, ROT_MAT
  prime_joint_comp: "rot" #rot
  canonicalize_samples: True

# for loading and continuing to train a pre-trained model
#input_model_path: "../tests/train_mdm/parkour_dataset_v_21_test01/checkpoints/model_30000.pkl"

train_loss_fn: "squared_l2"
test_loss_fn: "squared_l2"

#key_bodies: ["left_foot", "right_foot", "left_hand", "right_hand"]
#key_bodies: []

autoregressive: True
teacher_forcing: False
teacher_forcing_ramping_epochs: 50000
teacher_forcing_max_chance: 0.5

# transformer network
# todo: make this a separate file
d_model: 1024
num_heads: 16
d_hid: 1024
num_layers: 6

#obs_mlp_layers: [1024, 1024]
target_mlp_layers: [512]

in_mlp_layers: [1024]
out_mlp_layers: [1024]

# geometric loss weights
w_simple_root_pos: 1.0
w_simple_root_rot: 1.0
w_simple_joint_rot: 0.5
w_simple_contacts: 1.0
w_simple_body_pos: 0.5
w_body_pos_consistency: 1.0
w_vel_root_pos: 0.5
w_vel_root_rot: 0.02
w_vel_joint_rot: 0.01
w_body_pos: 0.5 #1.0 # 1/15 * 1/3
w_body_rot: 0.1
w_body_vel: 0.03
w_foot_contact: 0.2
w_target: 0.02
w_hf: 15.0
w_floor_height: 5.0

# target task and hf loss only loss chance
ood_chance: 0.1

use_pos_loss: True
# use_foot_contact_loss: False
use_hf_collision_loss: False
use_target_loss: False

motion_lib_file: "data/motions/climb/motions.yaml"
sampler_save_filepath: "output/climb/sampler.pkl"
output_dir: "output/climb/"
char_file: "data/assets/humanoid.xml"
sequence_duration: 0.5 # seconds
sequence_fps: 30


# Condition tokens
prev_state_noise_ind_chance: 0.5 # higher means more likely to use clean signal when training
num_prev_states: 2
use_heightmap_obs: True
use_saved_heightmaps: True
use_hf_augmentation: True
#use_relative_heightmap: True # If this is true, local heightfield's height is relative to center height

# options: "RELATIVE_TO_ROOT_FLOOR", "RELATIVE_TO_ROOT"
relative_z_style: "RELATIVE_TO_ROOT"

# For augmenter
hf_augmentation_mode: "MAXPOOL_AND_BOXES"
max_num_boxes: 4
box_min_len: 2
box_max_len: 12
hf_maxpool_chance: 0.15 # will be rolled 3 times
hf_max_maxpool_size: 10
hf_change_height_chance: 0.1
#augment_heights: [-0.6, 0.6]

angle_noise_scale: 0.01
pos_noise_scale: 0.01

# use_target_obs: True
use_target_obs: False
#target_type: "XY_POS"
target_type: "XY_DIR"
target_dir_len_eps: 0.1
target_dir_heading_eps: 0.5
future_pos_noise_scale: 0.05 # using normal distribution

use_feature_vector: False
feature_vector_mlp_layers: [1024]
predict_floor_heights: True

heightmap:
  horizontal_scale: 0.2
  local_grid:
    num_x_neg: 10
    num_x_pos: 20
    num_y_neg: 15
    num_y_pos: 15

  max_h: 3.0

#null_box_obs_range_x: [4, 2]
cnn:
  net_name: "cnn_31xy_4layer_c64_out64"

future_window_min: 0.4 # seconds
future_window_max: 1.5 # seconds